### ISSUE TITLE
DataQualityTest Categorization

### ISSUE THREAD

**Issue by Vixtir** [opendatadiscovery/opendatadiscovery-specification#62]
### **Goal**

The goal is to categorize tests into two distinct categories:

1. **Assertion Tests:** These are tests that run at specific points in time and primarily validate specific conditions or behaviors.
2. **Anomaly Detection Tests:** These tests are designed to identify anomalies or deviations in data, and their outcomes are influenced by the temporal aspects and lifetime of the data.

### **Decisions**

1. Due to property `type` already used to specify expectation type by name, decided to introduce new property `category`.

### **Option 1: Categorizing Anomaly Detection Subtypes**

In this option, we establish and classify common subtypes for anomaly detection.

**Pros:**

- Simplifies the process of grouping tests by their subtypes because all possible values are predefined.

**Cons:**

- Requires specification changes to incorporate new subtypes, which may involve additional administrative effort.

**Specification:**

```yaml
...
DataQualityTestExpectationCategory:
    type: string
    enum:
      - ASSERTION
      - VOLUME_ANOMALY
      - FRESHNESS_ANOMALY
      - COLUMN_VALUES_ANOMALY
      - SCHEMA_CHANGE

DataQualityTestExpectation:
    type: object
    properties:
      type:
        type: string
        example: "expect_table_row_count_to_be_between"
      category:
          $ref: '#/components/schemas/DataQualityTestExpectationCategory'
    additionalProperties:
      type: string
...
```

**Code Example:**

```python
test_anomaly=DataQualityTestExpectation(
	type="volume_anomalies",
	category=DataQualityTestExpectationCategory.VOLUME_ANOMALY
)

test_assertion=DataQualityTestExpectation(
	type="expect_table_row_count_to_be_between",
	category=DataQualityTestExpectationCategory.ASSERTION
)
```

**Option 2. Simplifying the Categorization**

In this approach, we define only the main categories, and the specific type of a test, whether it's an `ASSERTION` or an `ANOMALY_DETECTION`, is determined by the `DataQualityTestExpectation.type` property.

Pros:

- Offers flexibility as any value can be assigned to the `DataQualityTestExpectation.type` property, allowing for custom categorization.
- Streamlines the process and avoids the need to create new subtypes for anomaly detection.

Cons:

- May make it challenging to group anomaly tests by their subtypes since the categorization is solely dependent on the `DataQualityTestExpectation.type` property.

**Specification:**

```yaml
...
DataQualityTestExpectationCategory:
      type: string
      enum:
        - ASSERTION
        - ANOMALY_DETECTION
DataQualityTestExpectation:
    type: object
    properties:
      type:
        type: string
        example: "expect_table_row_count_to_be_between"
      category:
          $ref: '#/components/schemas/DataQualityTestExpectationCategory'
    additionalProperties:
      type: string
...
```

**Code Example:**

```python
test_anomaly=DataQualityTestExpectation(
	type="volume_anomalies",
	category=DataQualityTestExpectationCategory.ANOMALY_DETECTION
)

test_assertion=DataQualityTestExpectation(
	type="expect_table_row_count_to_be_between",
	category=DataQualityTestExpectationCategory.ASSERTION
)
```

**Comment by RamanDamayeu** [comment]
I like option Option 1: Categorizing Anomaly Detection Subtypes! IMHO it makes things more descriptive.
